/**
 * Generates `lib/form-builder/companion-sources.generated.ts`: a map from each
 * companion component's emitted filename to its source text, read verbatim from
 * the real component file. The code generator emits these as standalone files,
 * so this keeps the generated output a single source of truth with the live
 * components — without relying on bundler `?raw` support (which Turbopack lacks).
 *
 * Runs automatically before dev/build/typecheck via the `pre*` scripts, so the
 * generated file is always fresh. Regenerate manually with `pnpm gen:companions`.
 *
 * To add a companion (e.g. a future rating input): add its path to
 * COMPANION_FILES here, then register it in COMPANION_BY_TYPE
 * (lib/form-builder/codegen-companions.ts).
 */
import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()

// The component files emitted as companions by the code generator.
const COMPANION_FILES = ["components/ui/password-input.tsx"]

const entries = COMPANION_FILES.map((rel) => {
  const source = fs.readFileSync(path.join(ROOT, rel), "utf8").trimEnd() + "\n"
  const filename = path.basename(rel)
  return `  ${JSON.stringify(filename)}: ${JSON.stringify(source)},`
}).join("\n")

const output = `// AUTO-GENERATED by scripts/generate-companion-sources.ts — do not edit.
// Regenerate with \`pnpm gen:companions\` (runs automatically before dev/build).

/** Source text of each companion component, keyed by emitted filename. */
export const COMPANION_SOURCES: Record<string, string> = {
${entries}
}
`

const outPath = path.join(
  ROOT,
  "lib/form-builder/companion-sources.generated.ts"
)
fs.writeFileSync(outPath, output)
console.log(
  `Wrote ${path.relative(ROOT, outPath)} (${COMPANION_FILES.length} companion(s)).`
)
